/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;

#define RCC_BASE	0x40021000
#define RCC_APB2ENR	(*(vuint32_t *)(RCC_BASE + 0x18))

#define GPIOA_BASE	0x40010800
#define GPIOA_CRH	(*(vuint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_IDR	(*(vuint32_t *)(GPIOA_BASE + 0x08))
#define GPIOA_CRL	(*(vuint32_t *)(GPIOA_BASE + 0x00))

#define GPIOB_BASE	0x40010C00
#define GPIOB_CRH	(*(vuint32_t *)(GPIOB_BASE + 0x04))
#define GPIOB_ODR	(*(vuint32_t *)(GPIOB_BASE + 0x0C))
#define GPIOB_CRL	(*(vuint32_t *)(GPIOB_BASE + 0x00))

void myWait(){
	for (int i = 0; i < 50000; i++);
}

int main(void)
{
	RCC_APB2ENR |= (1 << 2); /* Enable IOPA */
	RCC_APB2ENR |= (1 << 3); /* Enable IOPB */
	GPIOA_CRH = 0;
	GPIOA_CRL = 0;
	GPIOB_CRH = 0;
	GPIOB_CRL = 0;

	/*CNFy[1:0]: Port x configuration bits (y= 8 .. 15)
These bits are written by software to configure the corresponding I/O port.
Refer to Table 20: Port bit configuration table.
In input mode (MODE[1:0]=00):
00: Analog mode
01: Floating input (reset state)
10: Input with pull-up / pull-down
11: Reserved
In output mode (MODE[1:0] > 00):
00: General purpose output push-pull
01: General purpose output Open-drain
10: Alternate function output Push-pull
11: Alternate function output Open-drain*/
	GPIOA_CRH &=~(0b11<<20);
	GPIOA_CRH |= 1 << 22; /* set A13 floating input */

	/*MODEy[1:0]: Port x mode bits (y= 8 .. 15)
These bits are written by software to configure the corresponding I/O port.
Refer to Table 20: Port bit configuration table.
00: Input mode (reset state)
01: Output mode, max speed 10 MHz.
10: Output mode, max speed 2 MHz.
11: Output mode, max speed 50 MHz.*/
	GPIOB_CRH |= 1 << 20; /* set B13 output */
	GPIOB_CRH &=~(0b11<<22);

	/*CNFy[1:0]: Port x configuration bits (y= 0 .. 7)
These bits are written by software to configure the corresponding I/O port.
Refer to Table 20: Port bit configuration table.
In input mode (MODE[1:0]=00):
00: Analog mode
01: Floating input (reset state)
10: Input with pull-up / pull-down
11: Reserved
In output mode (MODE[1:0] > 00):
00: General purpose output push-pull
01: General purpose output Open-drain
10: Alternate function output Push-pull
11: Alternate function output Open-drain*/
	GPIOA_CRL &=~(0b11<<4);
	GPIOA_CRL |= 1 << 6; /*set A1 floating input*/

	/*MODEy[1:0]: Port x mode bits (y= 8 .. 15)
These bits are written by software to configure the corresponding I/O port.
Refer to Table 20: Port bit configuration table.
00: Input mode (reset state)
01: Output mode, max speed 10 MHz.
10: Output mode, max speed 2 MHz.
11: Output mode, max speed 50 MHz.*/
	GPIOB_CRL |= 1 << 4; /* set B1 output */
	GPIOB_CRL &=~(0b11<<6);

	while(1){
		if (((GPIOA_IDR & (1 << 1)) >> 1) == 0){
			GPIOB_ODR ^= 1 << 1;
			while (((GPIOA_IDR & (1 << 1)) >> 1) == 0); /* Single Press */
		}
		if (((GPIOA_IDR & (1 << 13)) >> 13) == 1){
			GPIOB_ODR ^= 1 << 13; /* Multiple Press */
		}
		myWait();
	}
}
