/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103x8_GPIO_Driver.h"

void clockInit(){
	RCC_GPIOA_CLK_EN(); /* Enable IOPA */
	RCC_GPIOB_CLK_EN(); /* Enable IOPB */
}

void GPIO_Init(){
	GPIO_PinConfig_t *PinConfig = NULL;

	/* PA1 input HighZ floating input (reset value) */
	PinConfig->pinNumber = GPIO_PIN_1;
	PinConfig->mode = GPIO_MODE_INPUT_FLOATING;
	MCAL_GPIO_Init(GPIOA, PinConfig);

	/* PA13 input HighZ floating input (reset value) */
	PinConfig->pinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOA, PinConfig);

	/* PB1 output push pull mode */
	PinConfig->pinNumber = GPIO_PIN_1;
	PinConfig->mode = GPIO_MODE_OUTPUT_PP;
	PinConfig->outputSpeed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, PinConfig);

	/* PB13 output push pull mode */
	PinConfig->pinNumber = GPIO_PIN_13;
	PinConfig->mode = GPIO_MODE_OUTPUT_PP;
	MCAL_GPIO_Init(GPIOB, PinConfig);
}

void myWait(){
	for (int i = 0; i < 50000; i++);
}

int main(void)
{
	clockInit();
	GPIO_Init();
	while(1){
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0){
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0); /* Single Press */
		}
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1){
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13); /* Multiple Press */
		}
		myWait();
	}
}

